### PR TITLE
Update geth.toml

### PR DESCRIPTION
**Pull request by thetroyharris**
Changing to match changes made by the geth team see: https://github.com/ethereum/go-ethereum/pull/29895/files

### CODE REVIEW

**Comment by Wolmin** [comment]
Hey @thetroyharris @JordyDutch - thank you for providing us this PR - to make sure that we are providing the values that are the same as default, we will need to first bump the versions across our services (LUKSO CLI, Docker repositories) - after we've done that, we will merge this PR as it is

**Comment by mxmar** [comment]
Related: https://github.com/ethereum/go-ethereum/commit/2613523cb510a2e3ab956214c447e95c8a3d2d56

**Comment by JordyDutch** [comment]
> Related: [ethereum/go-ethereum@2613523](https://github.com/ethereum/go-ethereum/commit/2613523cb510a2e3ab956214c447e95c8a3d2d56)

@mxmar What if we just remove all `GasPrice` flags to always use the defaults? We also don't use it for Erigon client

**Comment by mxmar** [comment]
Thanks for your input @JordyDutch.

I was thinking the same, but I see that some 3rd parties rely on our network-configs, so if they don't see the flag, they won't make them configurable (Dappnode made gasprice configurable at my request). I'd prefer to leave the flags and just set them to the default value. This means that some 3rd parties (or devs) will make it configurable by default or will start speaking to the network team about it (because they see the flag in network-configs).

**Comment by mxmar** [comment]
> > Related: [ethereum/go-ethereum@2613523](https://github.com/ethereum/go-ethereum/commit/2613523cb510a2e3ab956214c447e95c8a3d2d56)
> 
> @mxmar What if we just remove all `GasPrice` flags to always use the defaults? We also don't use it for Erigon client

Thanks for your input @JordyDutch.

I was thinking the same, but I see that some 3rd parties rely on our network-configs, so if they don't see the flag, they won't make them configurable (Dappnode made gasprice configurable at my request). I'd prefer to leave the flags and just set them to the default value. This means that some 3rd parties (or devs) will make it configurable by default or will start speaking to the network team about it (because they see the flag in network-configs).

**Comment by JordyDutch** [comment]
> > > Related: [ethereum/go-ethereum@2613523](https://github.com/ethereum/go-ethereum/commit/2613523cb510a2e3ab956214c447e95c8a3d2d56)
> > 
> > 
> > @mxmar What if we just remove all `GasPrice` flags to always use the defaults? We also don't use it for Erigon client
> 
> Thanks for your input @JordyDutch.
> 
> I was thinking the same, but I see that some 3rd parties rely on our network-configs, so if they don't see the flag, they won't make them configurable (Dappnode made gasprice configurable at my request). I'd prefer to leave the flags and just set them to the default value. This means that some 3rd parties (or devs) will make it configurable by default or will start speaking to the network team about it (because they see the flag in network-configs).

Got it @mxmar, sounds good. But in this case it would also be good to add the flags and set to default for Erigon and Nethermind? 

Because now we have 2 clients with and 2 clients without the flags.

**Comment by mxmar** [comment]
> > > > Related: [ethereum/go-ethereum@2613523](https://github.com/ethereum/go-ethereum/commit/2613523cb510a2e3ab956214c447e95c8a3d2d56)
> > > 
> > > 
> > > @mxmar What if we just remove all `GasPrice` flags to always use the defaults? We also don't use it for Erigon client
> > 
> > 
> > Thanks for your input @JordyDutch.
> > I was thinking the same, but I see that some 3rd parties rely on our network-configs, so if they don't see the flag, they won't make them configurable (Dappnode made gasprice configurable at my request). I'd prefer to leave the flags and just set them to the default value. This means that some 3rd parties (or devs) will make it configurable by default or will start speaking to the network team about it (because they see the flag in network-configs).
> 
> Got it @mxmar, sounds good. But in this case it would also be good to add the flags and set to default for Erigon and Nethermind?
> 
> Because now we have 2 clients with and 2 clients without the flags.

You are right, `Nethermind` is missing the default flag. @Wolmin can add in next PR or you can add here. `Erigon` is still missing: https://github.com/erigontech/erigon/issues/9945

**Review by mxmar — APPROVED** [review]

**Comment by mxmar** [comment]
@thetroyharris Please solve conflicts and we can merge this PR.

**Comment by mxmar** [comment]
@thetroyharris @JordyDutch I'm closing this, because https://github.com/lukso-network/network-configs/pull/143 PR has been merged :heavy_check_mark:

**Pull request closed without merging**
